name: Imports (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test imports
      run:
        python -m pip install --upgrade pip
        pip install .
        pip install .[snowflake]
        pip install .[bigquery]
        pip install .[redshift]
        pip install .[postgres]
        pip install .[trino]
        pip install .[presto]
        pip install .[pyspark]
        pip install .[dbt]
        pip install .[docker]


# EOF