name: mypy

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r style_requirements.txt     
    - name: mypy
      run: |
        mypy prism/cli prism/event_managers/ prism/infra prism/parsers prism/profiles prism/spark


# EOF